### ISSUE TITLE
Reconstruction speed of ReconFormer

### ISSUE THREAD

**Issue by rederyang** [guopengf/ReconFormer#1]
First of all, congratulations on this great work!
Besides, ReconFormer proposed in the paper can outperform other SOTA methods with respect to image quality, but what about the reconstruction speed? Could it apply to dynamic MRI? Since ReconFomer's reconstruction speed is not reported in the paper.
Hope for your reply!

**Comment by rederyang** [comment]
Sorry, my question is not clear. By "dynamic MRI", I mean real-time MRI.

**Comment by guopengf** [comment]
Hi, the inference time is about 0.1 second per 2D image on my workstation. Currently, we are still working more experiemnts and preparing the supplementary materials.  We will provide more computional details of different methods, such as FLOPs, in the supplementary materials.

**Comment by rederyang** [comment]
I see. 
Thanks!
