### ISSUE TITLE
关于显存至少得有多大可以进行模型训练

### ISSUE THREAD

**Issue by VincyDa** [guopengf/ReconFormer#2]
同学您好，有注意到你这边用的是48G的RTX8000显卡，我这边大概仅有20g的显存，想问问你那边有没有尝试过其他较小显存显卡上面跑

**Comment by guopengf** [comment]
把batch size变小应该可以。

**Comment by VincyDa** [comment]
好的，我去试试，感谢！
________________________________
发件人: Pengfei Guo ***@***.***>
发送时间: 2023年2月16日 23:58
收件人: guopengf/ReconFormer ***@***.***>
抄送: VincyDa ***@***.***>; Author ***@***.***>
主题: Re: [guopengf/ReconFormer] 关于显存至少得有多大可以进行模型训练 (Issue #2)


把batch size变小应该可以。

―
