### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by jmzhang79** [guopengf/ReconFormer#4]
Hi, thanks for sharing the code and data.
I have a question. What's mean "two" in the proposed dataset? Thank you.
![image](https://github.com/guopengf/ReconFormer/assets/60723190/3e09e776-316c-455f-b0f2-01cf0c05d190)
![image](https://github.com/guopengf/ReconFormer/assets/60723190/fd3d0cc7-6d3b-48c3-b41a-8bbd2ab5ffe2)

**Comment by jmzhang79** [comment]
And what is the difference between "PD"/"PD1"/"PD2"/"two"? Thank you.

**Comment by guopengf** [comment]
Hi, I have removed those folders created by Guest Contributor.

**Comment by jmzhang79** [comment]
It seems that there are still some files created by Guest Contributor in PD folder

**Comment by jmzhang79** [comment]
It seems that there are still some files created by Guest Contributor in PD folder

**Comment by guopengf** [comment]
I see. I just removed them all. I've included the new link and password in the updated README.

**Comment by jmzhang79** [comment]
Thank you!
